### ISSUE TITLE
BYOC: publish list of permission in docs referenced in Terraform

### ISSUE THREAD

**Issue by robert-s-lee** [gridai/grid-docs#21]
https://docs.grid.ai/platform/about-these-features/adding-custom-cloud-credentials needs to list permission requested by https://github.com/gridai/terraform-aws-gridbyoc.git script.    https://github.com/gridai/terraform-aws-gridbyoc/blob/main/main.tf has the list of permissions:

- "eks:*",        
- "ecr:*",
-  "arn:aws:iam::aws:policy/AmazonEC2FullAccess",    
-  "arn:aws:iam::aws:policy/AmazonGuardDutyFullAccess",    
- "arn:aws:iam::aws:policy/AmazonRoute53ResolverFullAccess",    
- "arn:aws:iam::aws:policy/AmazonS3FullAccess",    
- "arn:aws:iam::aws:policy/AmazonSNSFullAccess",    
- "arn:aws:iam::aws:policy/AmazonSQSFullAccess",    
- "arn:aws:iam::aws:policy/AmazonVPCFullAccess",    
- "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess",    
- "arn:aws:iam::aws:policy/IAMFullAccess",

**Comment by pchitale1** [comment]
@robert-s-lee, which step will this belong to, please clarify, thanks

**Comment by pchitale1** [comment]
Updated, please check Robert
