### ISSUE TITLE
BYOC: remove WebUI registration (or put a note to skip)

### ISSUE THREAD

**Issue by robert-s-lee** [gridai/grid-docs#22]
Propose we either delete this step in the docs or put a note to skip this step.  https://docs.grid.ai/platform/about-these-features/adding-custom-cloud-credentials#add-custom-cloud-credential-1

@nmiculinic @gridai/qa

**Comment by pchitale1** [comment]
Will be added to docs this week, thanks @robert-s-lee

**Comment by pchitale1** [comment]
Updated instructions in Gitbook
