### ISSUE TITLE
image-classification-with-imagenet: ways to reduce 6+ hours to prepare demo

### ISSUE THREAD

**Issue by robert-s-lee** [gridai/grid-docs#26]
https://docs.grid.ai/examples/vision/image-classification-with-imagenet requires `+6 hours if you need to download and process ImageNet`.  Is there pre-created datastore that can be shared?

**Comment by pchitale1** [comment]
Imagenet guidelines for making sure there is permission to download is here: https://image-net.org/signup.php?next=download-images
