### ISSUE TITLE
Julia: examples graphics has python when it should be empty for Julia

### ISSUE THREAD

**Issue by robert-s-lee** [gridai/grid-docs#31]
https://docs.grid.ai/products/run-run-and-sweep-github-files/running-julia-programs video show `python demo.jl`.  the actual run show `demo.jl`

<img width="437" alt="Screen Shot 2021-06-23 at 6 06 38 PM" src="https://user-images.githubusercontent.com/6315124/123174854-cefa9b80-d44e-11eb-90c9-68a40c11b1d5.png">

**Comment by pchitale1** [comment]
Updated gif file in Gitbook
