### ISSUE TITLE
Coin Market Cap Price Forecasting: grid run badge does not result in runnable experiment

### ISSUE THREAD

**Issue by robert-s-lee** [gridai/grid-docs#34]
https://docs.grid.ai/examples/time-series/price-forecasting below is not accepted as runnable.

```
python train.py \
run --grid_config .grid/config.yml train.py --max_epochs 100 --data_path /dataset/cryptocurrency_prices.csv --learning_rate 'uniform(0,0.03,5)' --hidden_size "[16,32,64]
```

<img width="437" alt="Screen Shot 2021-06-24 at 9 03 05 AM" src="https://user-images.githubusercontent.com/6315124/123267441-0313a200-d4cb-11eb-8fa2-34c913b72e39.png">

**Comment by rusenask** [comment]
missing `"` in the end?

**Comment by robert-s-lee** [comment]
yes, missing `"`,  remove `run --grid_config .grid/config.yml train.py`, and `--data_path /dataset/cryptocurrency_prices.csv`.      the config.yaml has to be moved into encoded URL and data has be downloaded from the script.

**Comment by robert-s-lee** [comment]
@rusenask what is the download URL for `cryptocurrency_prices.csv`?

**Comment by robert-s-lee** [comment]
NVM.  found the file in https://github.com/gridai/gridai-timeseries-forecasting-demo

**Comment by pchitale1** [comment]
@robert-s-lee looking into this, the link for example and the one included in docs does not match, fixing the link. Badge related fixes will be coming in the product soon
