### ISSUE TITLE
Text Classification: make it run without datastore

### ISSUE THREAD

**Issue by robert-s-lee** [gridai/grid-docs#35]
https://docs.grid.ai/examples/nlp/text-classification   Cannot with Grid AI Run Badge when there is datastore.  Modify script to download if the data is not available.  https://github.com/gridai/grid-text-classification/blob/main/train.py

**Comment by pchitale1** [comment]
Ability to run with datastore mounted is shown in the example. 
When badge fixes are in the product, we will be able to run with badge
