### ISSUE TITLE
GitHub Enterprise support?

### ISSUE THREAD

**Issue by elgalu** [gridai/grid-docs#66]
Hi, do you support GitHub Enterprise on the self-hosted version?

It should be as simple as making the host name `github.com` configurable.

Thanks.

**Comment by essiequoi** [comment]
Hi there @elgalu 
Appreciate the question and apologies for the long-wait time. 
If you're still looking for a solution here, we recommend running experiments from a local directory using the `grid run --localdir` option. 
Please let me know if you have questions about this.
