### ISSUE TITLE
document hard link work, but not sym link in datastore

### ISSUE THREAD

**Issue by robert-s-lee** [gridai/grid-docs#74]
Assume there any many files and directories in the current directories.  If a subset of them is required in datastore, then `ln` can be used to specify the subset.  `ln` supports hard and sym links.  hard links work.  sym links do not work.

- hard link example
```
mkdir tmp2
cd tmp2
ln ../test1.txt
ln ../test2.txt
grid datastore create --source . --name hardlink
│ prod-2     │     hardlink │       1 │   1.0 MB │ 2021-11-23 22:01 │ sangkyulee@gmail.com │ Succeeded │
grid session create --name hardlinktest --datastore_name hardlink
# wait for session to come up
grid seesion ssh hardlinktest
cat /home/jovyan/hardlink/*
cat: /home/jovyan/hardlink/lost+found: Is a directory
test1.txt
test2.txt
```

- sym link example [ does not work ]
```
echo "test1" > test1.txt
echo "test2" > test2.txt
mkdir tmp
cd tmp
ln -s ../test1.txt test1.txt
ln -s ../test2.txt test2.txt
cat *
grid datastore create --source . --name symlink

│ prod-2     │      symlink │       1 │  0 Bytes │ 2021-11-23 21:56 │ sangkyulee@gmail.com │    Failed │
```

**Comment by rusenask** [comment]
hard link is just a complete copy of a file, no additional handling is needed for it, therefore it works. As for sym links, let's just document that these are not supported and that's. However we should ignore them and not fail the upload, maybe also print a message that it was ignored in the CLI.

**Comment by essiequoi** [comment]
@oojo12 can you review this one?

**Comment by essiequoi** [comment]
To be addressed in next docs sprint. Thanks!
